### ISSUE TITLE
베트남DB / 1차 리뷰 후 수정예정사항 정리

### ISSUE THREAD

**Issue by heozeop** [gomicorp/EcommerceAPI#119]
1. request exception 중에 상수와 리터럴 문자열 섞여있는 것 상수로 통일
2. 배열-데이터 형태를 아까 보여주신 방법으로 변경

**Comment by PLUX-KR** [comment]
1. ExternalChannelCartItem에 있는 external_option_id 필드 정리
2. ExternalChannelProductId 클래스명 변경
3. 외부채널과 관련된 클래스 이름 및 계층구조 변경(모듈화)
@yhk1038

**Comment by heozeop** [comment]
맨 윗글의 1,2번은 아래 커밋에서 수정하였습니다.
ae11fe6bdae76173c9dabb7291fba9ef15ea5606

**Comment by PLUX-KR** [comment]
4번은 5b68852d52d3e0c9f1697a7ff591a85297c0d557 에서 수정했습니다

**Comment by PLUX-KR** [comment]
4번 수정했습니다 
470a036c464dc76e318c1f9c6d546234057977b5 ~ 2ae6f2510eea3288b3fad3a4ed033a0538d877eb 까지 입니다
