### ISSUE TITLE
[긴급] 브랜드 생성하는 api에 동작하지 않는 기능이 있습니다.

### ISSUE THREAD

**Issue by wonseokyang** [gomicorp/EcommerceAPI#88]
feat/partner에서 브랜드 생성하는 endpoint에 country가 베트남으로 POST를 날린 경우 반응이 없습니다.
(태국은 정상 동작합니다.)
```
url : /partner/brands.json
method : POST
data : {
    brand: {
      company_id: params.company_id,
      country_id: 1,
      logo: null,
      name: {
        ko: params.name_ko,
        en: params.name_en,
        th: params.name_th,
      },
    },
  };
```
혹시 정상적으로 구현되어 있는지 빠르게 확인 부탁합니다.

**Comment by yhk1038** [comment]
### 잘 됩니다.

![image](https://user-images.githubusercontent.com/13119624/91531089-2cb17a80-e947-11ea-9463-ccb58b70d122.png)


전달 주신 리퀘스트의 `/partner/brand.json` 을 `/partner/brands.json` 로 복수형으로 고쳐서 다시 시도해보세요.

참고로 별도로 안내가 없는 경우, 일반적으로 라우팅 상에서 리소스의 이름은 복수형으로 정의되고 있으니 작업 간에 참고 바랍니다.

**Comment by yhk1038** [comment]
@wonseokyang 참, 추가적으로 해당 리퀘스트 엔드포인트는 로그인 검증을 수행하고 있습니다.

로그인을 통해 토큰을 발급 받은 후 `Authorization` 헤더에 넣고 요청을 수행해주셔야 한다는 점에 유의 바랍니다!

이 이슈는 해결 된 것으로 간주하고 닫도록 하겠습니다!

**Comment by yhk1038** [comment]
아 원래 태국은 정상 동작하고 문제 상황은 베트남이군요, 다시 열겠습니다.

**Comment by wonseokyang** [comment]
![스크린샷 2020-08-28 오후 4 08 35](https://user-images.githubusercontent.com/35683464/91532130-d2b1b480-e948-11ea-8bfb-d70f9d492253.png)

위 파라미터로 post 날렸고, 토큰도 함께 날렸습니다.

**Comment by yhk1038** [comment]
@wonseokyang 원석님은 로컬에 country_id 가 1이 지금 베트남인거죠? 제껀 태국이라 오해가 좀 있었나봐요

**Comment by wonseokyang** [comment]
@yhk1038 네네 맞아요.
의심되는 부분은 partner/brands.json으로 get할 때 백엔드 쪽에서 모든 국가에 있는 브랜드를 가져오지 못하는 것 같아요.

**Comment by yhk1038** [comment]
@wonseokyang 
혹시 request body 에 name field Locale 중에 vi 키가 빠져있기 때문은 아닌지 확인 해봤으면 좋겠는데 테스트 해보시고 다시 알려주실 수 있나요?

**Comment by yhk1038** [comment]
@wonseokyang 
우선 제 쪽에서는 같은 파라미터 구조 하에서 아래와 같이 베트남 국가설정 상태로도 정상 생성 되는 것 확인 했습니다.

![image](https://user-images.githubusercontent.com/13119624/91533695-4a80de80-e94b-11ea-8738-376457751855.png)

혹시 로컬에 실행중인 레일즈 서버의 로그 중에, 해당 생성 요청에 해당하는 Request 로그 블록을 캡쳐해서 전달해주시면 분석에 도움이 될 것 같습니다.

**Comment by wonseokyang** [comment]
@yhk1038 이제는 currentUser에 귀속된 브랜드가 아닌 모든 브랜드를 받아오는 것으로 확인됩니다! 아직 해결되지 않았습니다.

**Comment by yhk1038** [comment]
@wonseokyang currentUser에 귀속된 브랜드가 아닌 모든 브랜드를 받아오는 문제는 다른 이슈로 생성하고 이 이슈는 종료하겠습니다!
